# Custom module command names. Split commands with a comma.
# These commands will be registered as the server commands.
# Do not leave this empty.
Command_Aliases: auction,auc,ah

# Database settings.
Database:
  # How often (in seconds) plugin/user data will be saved automatically?
  # Set this to -1 to disable.
  Auto_Save_Interval: -1
  # How often (in minutes) plugin/user data will be synchronized automatically?
  # This means, that every X minutes the plugin will reload current data (fully or partially) from the database.
  # This option is useless for SQLite or if you don't share the same data between multiple servers with MySQL.
  # Set this to -1 to disable.
  Sync_Interval: 30
  # Database type.
  # Allowed: SQLITE, MYSQL
  Type: SQLITE
  # Database table prefix. Do not leave empty.
  Table_Prefix: excellentshop_auction
  # MySQL database settings.
  MySQL:
    # Your user name for the database access.
    Username: root
    # Your password for the database access.
    Password: root
    # Database host URL. Don't forget to set the port.
    Host: 'localhost:3306'
    # Database name.
    Database: minecraft
  # SQLite database settings.
  SQLite:
    # Database file name.
    # You can use sub-folders, like '/myfolder/data.db'
    FileName: auction.db
  # Database purge (clean) settings.
  Purge:
    # Enable/Disable auto-purge.
    Enabled: true
    # This setting is defines how 'old' the entry should be to purge it from the database.
    # This setting value can have different meanings for different database configs (days, months, etc.).
    # For Auction Listings, it's in days (from listing purchase/expire date).
    For_Period: 30

# Main auction settings.
Settings:
  # Date format for listings.
  # https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
  Date_Format: MM/dd/yyyy HH:mm:ss
  # List of worlds, where auctions will be disabled.
  Disabled_Worlds:
    - world1
    - world_name
  # List of GameModes, in which players will be unable to put items on auction.
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/GameMode.html
  Disabled_Gamemodes:
    - CREATIVE
    - SPECTATOR
  # Auction currency settings.
  Currency:
    # Currency unique identifier (the same as currency config file name).
    # All available currencies are located in the /currency/ plugin sub-folder.
    vault:
      # When 'true', makes this currency as default Auction currency.
      # This currency will be used when no other currencies are available.
      # Only one currency can be default at the same time.
      Default: true
      # When 'true', enables this currency for usage in Auction.
      Enabled: true
      # When 'true', a player must have permission to use this currency on Auction.
      # https://github.com/nulli0n/ExcellentShop-spigot/wiki/Permissions
      Need_Permission: false
  # Listing settings.
  Listings:
    # How long (in seconds) the listing will stay on auction until it become 'expired' and will be removed
    # from the main Auction GUI.
    Expire_In: 604800
    # When 'true', broadcasts a message when a new listing is added.
    Announce: false
    # Price settings.
    Price:
      # Price settings per each auction currency.
      Per_Currency:
        # Currency unique identifier (the same as currency config file name).
        # All available currencies are located in the /currency/ plugin sub-folder.
        vault:
          # Minimal price a player can set for a listing.
          # Set -1 for no limits.
          Min: 1.0
          # Maximal price a player can set for a listing.
          # Set -1 for no limits.
          Max: 1000000.0
      # Price settings for specified item material types.
      Per_Material:
        # Material name.
        # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
        DIAMOND:
          # Minimal price a player can set for a listing.
          # Set -1 for no limits.
          Min: 250
          # Maximal price a player can set for a listing.
          # Set -1 for no limits.
          Max: -1
    # Tax settings.
    Tax:
      # Tax amount (in percent of the listing price) that player will have to pay when adding an item on auction.
      On_Listing_Add: 10.0
      # Tax amount (in percent of the listing price) that will be deducted from the reward amount that owner will claim.
      On_Listing_Purchase: 0.0
    # How many listings a player with certain permission group can put at the same time.
    # Use '-1' for unlimited amount.
    # Make sure that group names here is the same as in your permissions plugin.
    Listings_Per_Rank:
      default: 10
      vip: 15
      admins: -1
    # List of Materials that can not be added on the Auction.
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Disabled_Materials:
      - BARRIER
      - BEDROCK
    # List of words, which when contained in item name, can not be added on the Auction.
    Disabled_Names:
      - item name
      - some word
    # List of words, which when contained in item lore, can not be added on the Auction.
    Disabled_Lores:
      - lore text
      - some word
