Title: '#5d6d7e&lShop Settings'
Size: 9
Inventory_Type: CHEST
Use_Mini_Message: false

Content:
  SHOP_CHANGE_NAME:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjVhMTlhZjBlNjFjYTQyNTMyYzA1OTlmYTBhMzkxNzUzZGY2YjcxZjlmYTRhMTc3ZjFhYTliMWQ4MWZlNmVlMiJ9fX0='
      Name: '#ee9aff&lShop Name'
      Lore:
        - '#ee9aff▪ #ddeceeCurrent: #ee9aff%shop_name%'
        - ''
        - '#ddeceeShop name to be displayed in'
        - '#ddeceeGUI and showcase.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffChange'
    Type: SHOP_CHANGE_NAME
    Slots: 0
    Priority: 5

  SHOP_CHANGE_TYPE:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmRhOTExNDM3YjRlY2ZhYTNjMTg5NDE2MjIxN2MwMWI2OGE1NWM4OWJiMmY0ZDQ5MjczNDVjZTVjNzk0In19fQ=='
      Name: '#ee9aff&lShop Type'
      Lore:
        - '#ee9aff▪ #ddeceeCurrent: #ee9aff%shop_type%'
        - ''
        - '#ddeceeSetting shop as #ee9affadmin shop#ddecee will'
        - '#ddeceemake it to have unlimited funds and items.'
        - ''
        - '#ff9a9a[!]#ddecee Make sure you have #ff9a9apermission#ddecee to use it.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffToggle'
    Type: SHOP_CHANGE_TYPE
    Slots: 1
    Priority: 5

  SHOP_CHANGE_TRANSACTIONS:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTgzOTg0ODU1M2NhYmVkOTc3ZThkNWNjOTc2ZDQ0Y2JhMmVhYWVmZTFkYTQ0NjE4N2U4NTJlZGVlMTZiODcwZSJ9fX0='
      Name: '#ee9aff&lTrade Mode'
      Lore:
        - '#ee9aff▪ #ddeceeBuying: #ee9aff%shop_buy_allowed%'
        - '#ee9aff▪ #ddeceeSelling: #ee9aff%shop_sell_allowed%'
        - ''
        - '#ddeceeEnable/disable certain operations in the shop.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffToggle Buying'
        - '#9af7ff▪ #ddeceeRight-Click: #9af7ffToggle Selling'
    Type: SHOP_CHANGE_TRANSACTIONS
    Slots: 2
    Priority: 5

  SHOP_CHANGE_PRODUCTS:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTAwZDI4ZmY3YjU0M2RkMDg4ZDAwNGIxYjFmOTViMzhkNDQ0ZWEwNDYxZmY1YWUzYzY4ZDc2YzBjMTZlMjUyNyJ9fX0='
      Name: '#ee9aff&lShop Products'
      Lore:
        - '#ddeceeHere you can #ee9affcreate#ddecee and #ee9affmanage'
        - '#ddeceeproducts of your shop.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffOpen'
    Type: SHOP_CHANGE_PRODUCTS
    Slots: 3
    Priority: 5

  SHOP_BANK:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg4OWNmY2JhY2JlNTk4ZThhMWNkODYxMGI0OWZjYjYyNjQ0ZThjYmE5ZDQ5MTFkMTIxMTM0NTA2ZDhlYTFiNyJ9fX0='
      Name: '#ee9aff&lShop Bank'
      Lore:
        - '#ee9aff▪ #ddeceeBalance: #ee9aff%shop_bank_balance%'
        - ''
        - '#ddeceeBank is used to store funds of your shop.'
        - '#ddeceeShop will #a5ff9again#ddecee funds from sales,'
        - '#ddeceeand #ff9a9aspend#ddecee them for purchases.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeLeft-Click: #9af7ffOpen'
    Type: SHOP_BANK
    Slots: 4
    Priority: 5

  SHOP_DELETE:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjQ2NWY4MGJmMDJiNDA4ODg1OTg3YjAwOTU3Y2E1ZTllYjg3NGMzZmE4ODMwNTA5OTU5N2EzMzNhMzM2ZWUxNSJ9fX0='
      Name: '#ff9a9a&lDelete Shop'
      Lore:
        - '#ddeceePermanently deletes the shop.'
        - ''
        - '#ff9a9a&lNOTE:'
        - '#ddeceeYou have to remove all items'
        - '#ddeceefrom the container first.'
        - ''
        - '#9af7ff&lActions:'
        - '#9af7ff▪ #ddeceeShift-Right: #9af7ffDelete'
    Type: SHOP_DELETE
    Slots: 8
    Priority: 5